Add support for parameters envs
medway-dev/django-splint-kovs pull request #4
Opened 2024-04-15 18:18 UTC by marcelo-bn

2024-04-15 18:50 UTC, alexandrefialho requested changes

2024-04-15 18:50 UTC, alexandrefialho commented on src/django_splint/utils/aws/sqs.py
> +        )
aqui maninho, coloca o default nos proprios kwargs, assim evita a condição do `or` 

tipo

```
def __init__(
    self, 
    aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
    aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
    aws_region_name=settings.AWS_DEFAULT_REGION
):
    self.client = boto3.client(
        service_name=self.service_name,
        aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
        aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
        region_name=settings.AWS_DEFAULT_REGION,
    )
```

2024-04-15 19:04 UTC, nvgerolomo commented on src/django_splint/utils/aws/sqs.py
> +        )
done ;)

2024-04-16 13:04 UTC, alexandrefialho approved these changes

2024-04-16 13:05 UTC, merged